---
title: "Abstract for Presentation"
author: "Alex Gould"
date: "`r Sys.Date()`"
output: word_document
---
\centering{Abstract for 3494 Presentation}

I decided to present the methods paper entitled: “Effect Sizes for Paired Data Should Use the Change Score Variability Rather Than the Pre-test Variability” By Scott J. Dankel and Jeremy P.  Loenneke of the University of Mississippi. This paper had two main objectives: to convince the audience that pre-test and post-test standard deviations don’t always tell the full story on the overall variability of the dataset,  as well as to convince the audience that the heterogeneity of the study sample can play a part in influencing effect size measurements and in turn paired t-test results.  

Through both objectives, Dankel and Loenneke advocated for the use of the effect size measurement Cohen’s dz over measurements like Hedge’s g, Cohen’s d, and Glass delta which use the likes of pre and post-test standard deviation to formulate their estimate. I believe that they made a well- informed argument for the most part regarding these topics, and I am excited to lay it out in presentation form, although, some of the measurements that they used did not line up with the data that is reported in their figures, specifically the standard deviation of the change scores (which , of course, was the measurement that built the foundation to this paper). I plan to re-analyze this data using the equations in this article and through my own sources to provide more accurate results and see if the significance that they reported still holds true.  I found this paper interesting because it deals with the idea of baseline and change scores in a different way than how I will explore these topics in my thesis. This concept, although not directly mentioned in the paper, also has roots in mathematical coupling, which I will also touch on in my paper in the future. In short, the effect size measures all use the baseline standard deviation in some respect, therefore the effect sizes seem to be naturally correlated with the effect sizes in this study which could lead to issues in accurate reporting.  