---
title: "Abstract for October 7th Presentation"
author: "Alex Gould"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf: default
  pdf_document: default
---

\doublespacing

I decided to present the methods paper entitled: “Effect Sizes for Paired Data Should Use the Change Score Variability Rather Than the Pre-test Variability” By Scott J. Dankel and Jeremy P.  Loenneke of the University of Mississippi. This paper had two main objectives: to convince the audience that pre-test and post-test standard deviations don’t always tell the full story on the overall variability of the dataset,  as well as to convince the audience that the heterogeneity of the study sample can play a part in influencing effect size measurements and in turn paired t-test results.  

Through both objectives, Dankel and Loenneke advocated for the use of the effect size measurement Cohen’s $d_z$ over measurements like Hedge’s $g$, Cohen’s $d$, and Glass's $\delta$ which use the likes of pre and post-test standard deviation to formulate their estimate. I believe that they made a well-informed argument for the most part regarding these topics, and I am excited to lay it out in presentation form, although, some of the measurements that they used did not line up with the data that is reported in their figures.

  Specifically, this was an issue with the standard deviation of the change scores (which was the measurement that built the foundation for this paper). Dankel and his team ironically define the measure using the correct equation later in the paper after using the wrong metric for the analysis.  I plan to re-analyze the standard deviation of the change scores using the aforementioned equation and through my own sources to provide more accurate results, and to see if the significance that they reported still holds.  
  
   I found this paper interesting because it deals with the idea of baseline and change scores in a different way than how I plan on exploring similar topics in my thesis. Overall, I am excited to present the complexities of their argument as well as the strengths and shortcomings of their analysis on Monday, October 7th at 5:30 pm in AUST 247. 
   
Keywords: Cohen's $d$, Hedge's $g$, Paired $t$ test, paired-sample testing, change-score mean, standard deviation of the change scores 

